### PR TITLE
Fix pg_repack build for PostgreSQL 11 and above

### PR DESCRIPTION
**Pull request by Melkij**
Hi
I will try fix build for recent releases. Build seems broken due [9a95a77d9d5d3003d2d67121f2731b6e5fc37336](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=9a95a77d9d5d3003d2d67121f2731b6e5fc37336) and [6337865f36da34e9c89aaa292f976bde6df0b065](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=6337865f36da34e9c89aaa292f976bde6df0b065) commits in PostgreSQL code: uppercase FALSE and TRUE constants was removed and was allowed using standart stdbool.h for boolean types.

Fix issue #181

Thank you

### CODE REVIEW

**Comment by Melkij** [comment]
Now test pass on travis.
Third change was in 2cd7084 / c629324 PostgreSQL commits: the way individual attributes in a
TupleDesc are stored / accessed was changed. TupleDescAttr was backpatched to supported branches and i forgot about 9.1, sorry.

**Comment by mbanck** [comment]
I'm still seeing a build failure here:

```
make[3]: Entering directory '/<<PKGBUILDDIR>>/lib'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DREPACK_VERSION=1.4.3 -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o repack.o repack.c
repack.c:28:10: fatal error: catalog/pg_inherits_fn.h: No such file or directory
 #include "catalog/pg_inherits_fn.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [<builtin>: repack.o] Error 1
```

**Comment by Melkij** [comment]
@mbanck thank you! You right, this was commit cefa3871534d2c467a520820c0ae3f002a46d8e4 in postgresql.
Sorry, i do not clean postgresql install dir and there was pg_inherits_fn.h in my setup.

**Comment by mbanck** [comment]
Thanks, it is working fine for me now - would be cool to also do a new release now that v11 is being released today.

**Comment by dvarrazzo** [comment]
It would be cool but postgres 11 should be added to travis

**Comment by dvarrazzo** [comment]
Trying that now: https://travis-ci.org/reorg/pg_repack/builds/443133547

**Comment by dvarrazzo** [comment]
@Melkij never mind: I'm already fixing this on my side and fixing the docs. Thank you very much for this merge request :)

**Comment by dvarrazzo** [comment]
Merged to master.

**Comment by Melkij** [comment]
Thank you!

**Pull request closed without merging**
