### PR TITLE
Add doc in Chinese

### PR DESCRIPTION
**Pull request by yansheng836**
Add doc in Chinese

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
@yansheng836 We've been discussing this patch. Is this a one-off translation, or do you plan to keep it updated if the need arrives to add further translations?

Also is there someone else who can contribute to this translation? We've had translation added in the past, and then abandoned.

**Comment by yansheng836** [comment]
Yes, I will always keep updating.

**Comment by dvarrazzo** [comment]
I would like to thank @yansheng836 for the proposal, but the translation in Chinese of the readme, but:

- this document is not published anywhere (the website code is not updated to expose it);
- we don't have a workflow for translations;
- needing to translate the docs makes releasing every feature more complex;
- if the translation doesn't happen in time, an user relying on it will just miss it, making a disservice to them and not reflecting well on us;
- I don't want to make wild generalization on the demographics of who uses a project, but I tend to believe that an user advanced enough as to needing to run pg_repack knows enough English to read our readme;
- none of us knows Chinese, so, as far as I know, the translation could be a list of swearing.

So I don't think we should merge this MR.

Note that the Japanese translation has similar shortcomings (with the difference that the original pg_reorg was written by Japanese people, so it made sense for them). If the latest versions have not been updated I propose to drop it too.

**Comment by yansheng836** [comment]
Ok, I see.

**Pull request closed without merging**
