### PR TITLE
Specify the storage option for TOAST table when create table.

### PR DESCRIPTION
**Pull request by MasahikoSawada**
The storage option such as AUTOVACUUM_VACUUM_SCALE_FACTOR can be
set to both heap table and TOAST table. But the storage parameter
for TOAST table had gone after repacked. This change create new
function get_storage_param which returns all storage paramters
including for TOAST table and OID setting.

Issue #10.

### CODE REVIEW

**Comment by MasahikoSawada** [comment]
There are some options to fix this issue. I've selected a option to make pg_repack specify the all storage parameter including parameters for TOAST table and OID setting when creating table. Please give me feedback.

**Comment by dvarrazzo** [comment]
It seems a good approach factoring out the parameters list into a function of its own. I'll sort out this conflict I've made in master.

**Comment by dvarrazzo** [comment]
I have rebased this branch to simplify history (dropping merges into master to solve conflicts in tests)

**Comment by MasahikoSawada** [comment]
Thank you for reviewing! Barring any objections, I'll merge this tomorrow.

**Pull request merged**
