### PR TITLE
pg_repack.c

### PR DESCRIPTION
**Pull request by MichaelDBA**
Fixes issue#260 where providing an invalid schema name returns with no error. It now returns a warning that no relations are found.

### CODE REVIEW

**Comment by andreasscherbaum** [comment]
@MichaelDBA Your PR changes all whitespaces, which makes it impossible to review the actual changes.
Can you please see that only the actual change is includes in the PR? Thanks

**Comment by MichaelDBA** [comment]
Should I withdraw and resubmit?

**Comment by andreasscherbaum** [comment]
I would assume that your editor automatically made the whitespace chances.
It's probably easier if you close this PR, figure out what your editor is doing, and create another PR.
But it's up to you.

**Comment by simi** [comment]
@MichaelDBA also force push works in here.

**Comment by andreasscherbaum** [comment]
@simi Yes - but force push does not fix the problem with the white spaces.
GitHub refused to open the changed file because too many changes in it.

**Comment by simi** [comment]
I mean once fixed, it is possible to force push and there is no need to open new PR.

Btw. it is possible to skip whitepaces in UI diff aka https://github.com/reorg/pg_repack/pull/341/files?diff=unified&w=1.

**Pull request closed without merging**
