### PR TITLE
Add github workflow

### PR DESCRIPTION
**Pull request by df7cb**
This runs the regression tests as a GitHub action.

### CODE REVIEW

**Comment by df7cb** [comment]
How it looks like: https://github.com/credativ/pg_repack/actions/runs/3144576352

**Comment by dvarrazzo** [comment]
@df7cb tests were cancelled at the first failure. Could you please add `fail-fast: false` to the grid? See [here](https://github.com/psycopg/psycopg/blob/013a5a44cde065f82ca63e7181db1d3e6f925a73/.github/workflows/tests.yml#L23-L26) for instance.

I would also remove the unsupported versions from the grid and starting from v10.

**Comment by df7cb** [comment]
Ah, good idea with disabling fail-fast, added in the last push. I had 9.5/9.6 in there because they work, but also removed them now.

Example run: https://github.com/credativ/pg_repack/actions/runs/3158761985

**Comment by Melkij** [comment]
Looks good to me.

PS: repack should pass the tests even on 9.4, I just checked it.

**Comment by dvarrazzo** [comment]
Merged, thank you!

**Comment by Melkij** [comment]
pg15 needs libzstd-dev, I pushed an update

**Comment by dvarrazzo** [comment]
Thank you, @Melkij, I was just about to ask :)

**Pull request merged**
